### ISSUE TITLE
Fehler nach der Installation 

### ISSUE THREAD

**Issue by WernerHAT** [romanlum/LoxBerry-Plugin-Unfi-Controller#1]
Hallo! Nach der an sich erfolgreichen Installation bekomme ich folgende Fehlermeldungen zugeschickt.
[PHP Warning:  syntax error, unexpected '!' in /opt/loxberry/config/system/general.cfg on line 54
in /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php on line 131
Warning: syntax error, unexpected '!' in /opt/loxberry/config/system/general.cfg on line 54
in /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php on line 131
PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: /opt/loxberry/config/system/general.cfg in /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php:133
Stack trace:
#0 /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php(890): Config_Lite->read('/opt/loxberry/c...', 0)
#1 /opt/loxberry/data/plugins/unifi/vendor/moay/loxberry-core/src/ConfigurationParser/ConfigurationParser.php(25): Config_Lite->__construct('/opt/loxberry/c...')
#2 /opt/loxberry/data/plugins/unifi/vendor/moay/loxberry-core/src/ConfigurationParser/SystemConfigurationParser.php(44): LoxBerry\ConfigurationParser\ConfigurationParser->__construct('/opt/loxberry/c...')
#3 [internal function]: LoxBerry\ConfigurationParser\SystemConfigurationParser->__construct(Object(LoxBerry\System\PathProvider))
#4 /opt/loxberry/data/plugins/unifi/vendor/symfony/dependency-injection/ContainerBuilder.php(1091): ReflectionClass->newInstanceArgs(Array)
#5 /opt/loxberry/data/plugins/unifi/vendor/symfony/depen in /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php on line 133
Fatal error: Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: /opt/loxberry/config/system/general.cfg in /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php:133
Stack trace:
#0 /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php(890): Config_Lite->read('/opt/loxberry/c...', 0)
#1 /opt/loxberry/data/plugins/unifi/vendor/moay/loxberry-core/src/ConfigurationParser/ConfigurationParser.php(25): Config_Lite->__construct('/opt/loxberry/c...')
#2 /opt/loxberry/data/plugins/unifi/vendor/moay/loxberry-core/src/ConfigurationParser/SystemConfigurationParser.php(44): LoxBerry\ConfigurationParser\ConfigurationParser->__construct('/opt/loxberry/c...')
#3 [internal function]: LoxBerry\ConfigurationParser\SystemConfigurationParser->__construct(Object(LoxBerry\System\PathProvider))
#4 /opt/loxberry/data/plugins/unifi/vendor/symfony/dependency-injection/ContainerBuilder.php(1091): ReflectionClass->newInstanceArgs(Array)
#5 /opt/loxberry/data/plugins/unifi/vendor/symfony/depen in /opt/loxberry/data/plugins/unifi/vendor/moay/config_lite/Config/Lite.php on line 133](url)

**Comment by romanlum** [comment]
Danke für den Fehlerbericht.
Welche Loxberry Version verwenden Sie denn?

**Comment by WernerHAT** [comment]
Hallo,
darauf habe ich natürlich vergessen: Loxberry v2.2.0.4, Docker v2.0.1
LG

**Comment by romanlum** [comment]
Können Sie mal schauen was in der Datei
 /opt/loxberry/config/system/general.cfg in Zeile 54 steht?

**Comment by romanlum** [comment]
Wenn es sich um ein Passwort handelt, bitte nicht posten
einfach den Text vor dem =

**Comment by WernerHAT** [comment]
Hallo, 
entschuldige die späte Rückmeldung.
Ja, in Zeile 54 ist das Kennwort. Es enthält ein !. Kann das das Problem sein?

**Comment by WernerHAT** [comment]
Das sind die Zeilen 131-134 in der Lite.php
       
$this->sections = parse_ini_file($filename, $this->processSections, $mode);
        if (false === $this->sections) {
            throw new Config_Lite_Exception_Runtime(
                'failure, can not parse the file: ' . $filename

**Comment by WernerHAT** [comment]
Update: Das Kennwort mit dem Sonderzeichen war das Problem.
